// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using R508_Revisions.Model.EntityFramework;

#nullable disable

namespace R508_Revisions.Migrations
{
    [DbContext(typeof(ProduitsDBContext))]
    partial class ProduitsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("R508_Revisions.Model.EntityFramework.Marque", b =>
                {
                    b.Property<int>("idMarque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mrq_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idMarque"));

                    b.Property<string>("nomMarque")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mrq_nom");

                    b.HasKey("idMarque");

                    b.ToTable("t_e_marque", "public");
                });

            modelBuilder.Entity("R508_Revisions.Model.EntityFramework.Produit", b =>
                {
                    b.Property<int>("idProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("prd_produit");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idProduit"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prd_description");

                    b.Property<int>("idMarque")
                        .HasColumnType("integer")
                        .HasColumnName("prd_idmarque");

                    b.Property<int>("idTypeProduit")
                        .HasColumnType("integer")
                        .HasColumnName("prd_idtype");

                    b.Property<string>("nomPhoto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prd_nomphoto");

                    b.Property<string>("nomProduit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prd_nom");

                    b.Property<int>("stockMax")
                        .HasColumnType("integer")
                        .HasColumnName("prd_stockmax");

                    b.Property<int>("stockMin")
                        .HasColumnType("integer")
                        .HasColumnName("prd_stockmin");

                    b.Property<int>("stockReel")
                        .HasColumnType("integer")
                        .HasColumnName("prd_stockreel");

                    b.Property<string>("uriPhoto")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("prd_uriphoto");

                    b.HasKey("idProduit");

                    b.HasIndex("idMarque");

                    b.HasIndex("idTypeProduit");

                    b.ToTable("t_e_produit", "public");
                });

            modelBuilder.Entity("R508_Revisions.Model.EntityFramework.TypeProduit", b =>
                {
                    b.Property<int>("idTypeProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tpp_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idTypeProduit"));

                    b.Property<string>("nomTypeProduit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tpp_nom");

                    b.HasKey("idTypeProduit");

                    b.ToTable("t_e_typeproduit", "public");
                });

            modelBuilder.Entity("R508_Revisions.Model.EntityFramework.Produit", b =>
                {
                    b.HasOne("R508_Revisions.Model.EntityFramework.Marque", "idMarqueNavigation")
                        .WithMany("Produits")
                        .HasForeignKey("idMarque")
                        .IsRequired()
                        .HasConstraintName("fk_produit_marque");

                    b.HasOne("R508_Revisions.Model.EntityFramework.TypeProduit", "idTypeProduitNavigation")
                        .WithMany("Produits")
                        .HasForeignKey("idTypeProduit")
                        .IsRequired()
                        .HasConstraintName("fk_produit_typeproduit");

                    b.Navigation("idMarqueNavigation");

                    b.Navigation("idTypeProduitNavigation");
                });

            modelBuilder.Entity("R508_Revisions.Model.EntityFramework.Marque", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("R508_Revisions.Model.EntityFramework.TypeProduit", b =>
                {
                    b.Navigation("Produits");
                });
#pragma warning restore 612, 618
        }
    }
}
